server:
  port: 8070

spring:
  application:
    name: msvc-series
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/seriescow
    username: postgres
    password: Borman15
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka


