server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: chapters
          uri: http://localhost:8090
          predicates:
            - Path=/api/chapter/**
        - id: series
          uri: http://localhost:8070
          predicates:
            - Path=/api/serie/**

eureka:
  client:
    register-with-eureka: false
